apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dev
  namespace: {{ .Values.mysql.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dev
  minReplicas: {{ .Values.mysql.hpa.minReplicas }}
  maxReplicas: {{ .Values.mysql.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: {{ .Values.mysql.hpa.targetType }}
          averageUtilization: {{ .Values.mysql.hpa.targetCPUUtilizationPercentage }}
