mysql:
  image:
    repository: abdlerazek/ourplant-db
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3306
  replicaCount: 1
  env:
    mysqlRootPassword: root
    mysqlDatabase: ourplant_db
  persistence:
    size: 200Mi
  namespace: mysql
  ResourceQuota:
    pods: 4
    requests.cpu: 2
    requests.memory: 2Gi
    limits.cpu: 4
    limits.memory: 4Gi
  hpa:
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 60
    targetType: Utilization